org: joaodev
app: aws-sls-api
service: aws-serverless-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    exclude:
      - '@aws-sdk/*'
    target: node20
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
